# docker compose to run the etl project
version:  '3.9'
services:
  db:
    build: /carepay_etl/mysql_docker_build
    ports:
      - "3306:3306"

#  etlapp:
#    build: ./carepay_etl
#    ports:
#      #i do not know this port for the bigquery
#
#    depends_on:
#      - "db"
#
  

