# docker compose to run the etl project
version:  '3.8'
services:
  db:
    build: ./carepay_etl/mysql_docker_build
    ports:
      - "3306:3306"

  etlapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"

  

